version: '3.8' 

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar123
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data      #Persistent storage
    networks:
      - cicd_net
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar123
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonaqube_extensions:/opt/sonarqube/extentions
    networks:
      - cicd_net
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"                               
      - "50000:50000"                              # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to run Docker commands     
    networks:
      - cicd_net
volumes:
  jenkins_home:
  postgres_data:
  sonarqube_data:
  sonaqube_extensions:
networks:
  cicd_net:
    driver: bridge
  